spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mariadb://database-123.czow0sc64bbc.ap-northeast-2.rds.amazonaws.com:3306/p3?useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver