spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mariadb://database-1.c7qk6qys8uq5.ap-northeast-2.rds.amazonaws.com:3306/p3?useUnicode=true&characterEncoding=utf8mb4&connectionCollation=utf8mb4_general_ci
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver